name: ColorDrops
main: me.stalexgaming.colordrops.Main
version: 1.0.1
description: ColorDrops is exclusively made for MineJoy
commands:
   colordrops:
      description: Core command for ColorDrops

depend: [WorldEdit]